# Generated by Django 3.1 on 2021-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flag1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='flag2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
