# Generated by Django 3.1 on 2021-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210503_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='xuz@gmail.com', max_length=50),
        ),
    ]
